# Generated by Django 4.2 on 2023-05-03 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Events",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("start", models.DateTimeField(blank=True, null=True)),
                ("end", models.DateTimeField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="FinancialAid",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "player_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "player_username",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("player_age", models.IntegerField(blank=True, null=True)),
                (
                    "player_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("annual_income", models.IntegerField(blank=True, null=True)),
                ("family_size", models.IntegerField(blank=True, null=True)),
                ("reason", models.TextField(blank=True, null=True)),
                ("status", models.CharField(default="Pending", max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("usertype", models.CharField(max_length=30)),
                ("age", models.IntegerField(blank=True, null=True)),
                ("height", models.IntegerField(blank=True, null=True)),
                ("weight", models.IntegerField(blank=True, null=True)),
                ("position", models.CharField(blank=True, max_length=30, null=True)),
                ("favorite_book", models.CharField(max_length=30)),
                ("favorite_food", models.CharField(max_length=30)),
                ("favorite_holiday", models.CharField(max_length=30)),
                ("due_payment", models.IntegerField(blank=True, null=True)),
                ("accepted", models.BooleanField()),
                ("monthly_payment", models.IntegerField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="Event Name")),
                (
                    "coach",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"usertype": "Coach"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="coached_teams",
                        to="app1.profile",
                    ),
                ),
                (
                    "players",
                    models.ManyToManyField(
                        blank=True,
                        limit_choices_to={"usertype": "Player"},
                        related_name="played_teams",
                        to="app1.profile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Stats",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.CharField(max_length=120, verbose_name="Position")),
                ("stat1", models.CharField(max_length=120, verbose_name="stat1")),
                (
                    "name",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"usertype": "Player"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="players",
                        to="app1.profile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Request",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
