# Generated by Django 3.2.18 on 2023-04-24 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usertype', models.CharField(max_length=30)),
                ('favorite_book', models.CharField(max_length=30)),
                ('favorite_food', models.CharField(max_length=30)),
                ('favorite_holiday', models.CharField(max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Event Name')),
                ('coach', models.ForeignKey(blank=True, limit_choices_to={'usertype': 'Coach'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coached_teams', to='app1.profile')),
                ('players', models.ManyToManyField(blank=True, limit_choices_to={'usertype': 'Player'}, related_name='played_teams', to='app1.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=False, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=120, verbose_name='Position')),
                ('stat1', models.CharField(max_length=120, verbose_name='stat1')),
                ('name', models.ForeignKey(blank=True,primary_key=True, limit_choices_to={'usertype': 'Player'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='app1.profile')),
            ],
        ),
    ]
