# Generated by Django 4.2 on 2023-04-30 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(name="Message",),
        migrations.DeleteModel(name="Room",),
    ]
