# Generated by Django 3.2.2 on 2023-04-29 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='monthly_payment',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
