# Generated by Django 4.2 on 2023-05-03 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="stats", name="stat1",),
        migrations.AddField(
            model_name="stats",
            name="APG",
            field=models.IntegerField(default=0, max_length=120, verbose_name="APG"),
        ),
        migrations.AddField(
            model_name="stats",
            name="BPG",
            field=models.IntegerField(default=0, max_length=120, verbose_name="BPG"),
        ),
        migrations.AddField(
            model_name="stats",
            name="MPG",
            field=models.IntegerField(default=0, max_length=120, verbose_name="MPG"),
        ),
        migrations.AddField(
            model_name="stats",
            name="PPG",
            field=models.IntegerField(default=0, max_length=120, verbose_name="PPG"),
        ),
        migrations.AddField(
            model_name="stats",
            name="RPG",
            field=models.IntegerField(default=0, max_length=120, verbose_name="RPG"),
        ),
        migrations.AddField(
            model_name="stats",
            name="SPG",
            field=models.IntegerField(default=0, max_length=120, verbose_name="SPG"),
        ),
        migrations.AddField(
            model_name="stats",
            name="TOVPG",
            field=models.IntegerField(default=0, max_length=120, verbose_name="TOVPG"),
        ),
        migrations.AddField(
            model_name="stats",
            name="rating",
            field=models.FloatField(blank=True, null=True, verbose_name="Rating"),
        ),
        migrations.CreateModel(
            name="Games",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Team1",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="games1",
                        to="app1.team",
                    ),
                ),
                (
                    "Team2",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="games2",
                        to="app1.team",
                    ),
                ),
                (
                    "Winner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="games3",
                        to="app1.team",
                    ),
                ),
            ],
        ),
    ]
