# Generated by Django 3.2.18 on 2023-04-17 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='coach',
            field=models.ForeignKey(blank=True, limit_choices_to={'usertype': 'Player'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coached_teams', to='app1.profile'),
        ),
        migrations.RemoveField(
            model_name='team',
            name='players',
        ),
        migrations.AddField(
            model_name='team',
            name='players',
            field=models.ManyToManyField(blank=True, limit_choices_to={'usertype': 'Player'}, related_name='played_teams', to='app1.Profile'),
        ),
    ]
