# Generated by Django 3.2.2 on 2023-04-29 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_profile_monthly_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='monthly_payment',
        ),
    ]
