# Generated by Django 3.2.2 on 2023-04-29 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_remove_profile_monthly_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='monthly_payment',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
