# Generated by Django 3.2.18 on 2023-04-18 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20230417_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='coach',
            field=models.ForeignKey(blank=True, limit_choices_to={'usertype': 'Coach'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coached_teams', to='app1.profile'),
        ),
    ]
