# Generated by Django 3.2.2 on 2023-04-30 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_profile_monthly_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='due_payment',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
