# Generated by Django 3.2.2 on 2023-04-30 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_alter_profile_due_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialAid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_requested', models.IntegerField()),
                ('reason', models.TextField()),
                ('documents', models.FileField(upload_to='financial_aid_documents/')),
                ('is_approved', models.BooleanField(default=False)),
                ('date_requested', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_requests', to='app1.profile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.profile')),
            ],
        ),
    ]
