# Generated by Django 3.2.2 on 2023-04-30 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_financialaid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialaid',
            name='amount_requested',
        ),
        migrations.RemoveField(
            model_name='financialaid',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='financialaid',
            name='date_requested',
        ),
        migrations.RemoveField(
            model_name='financialaid',
            name='documents',
        ),
        migrations.RemoveField(
            model_name='financialaid',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='financialaid',
            name='user',
        ),
        migrations.AddField(
            model_name='financialaid',
            name='annual_income',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialaid',
            name='family_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialaid',
            name='player_age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialaid',
            name='player_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='financialaid',
            name='player_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='financialaid',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
