# Generated by Django 3.2.2 on 2023-04-30 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app1', '0009_alter_financialaid_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialaid',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='financial_aid', to=settings.AUTH_USER_MODEL),
        ),
    ]
