# Generated by Django 3.2.2 on 2023-04-30 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_alter_financialaid_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialaid',
            name='user',
        ),
    ]
