# Generated by Django 3.2.2 on 2023-04-30 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_remove_financialaid_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialaid',
            name='player_username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
