# Generated by Django 3.2.2 on 2023-04-30 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_alter_financialaid_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialaid',
            name='status',
            field=models.CharField(default='Pending', max_length=100),
        ),
    ]
